### PR TITLE
chore: update nexus-staging-maven-plugin

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
This should apply the fix of https://issues.sonatype.org/browse/OSSRH-66257

### CODE REVIEW

**Comment by rix0rrr** [comment]
Did you get a chance to try if this actually fixes it? In another repository of ours, we also had to apply the other workaround mentioned on the Sonatype JIRA:

https://github.com/cdklabs/aws-delivlib/pull/1331

**Comment by DanielMSchmidt** [comment]
No I haven't, I fixed it by adding the same flags in our core library

**Comment by DanielMSchmidt** [comment]
But a newer version can't hurt, can it?

**Comment by rix0rrr** [comment]
> But a newer version can't hurt, can it?

Ha 😁. No, I suppose not. I'm fine with merging this, as long as we're all aware that this by itself is probably not going to fix anything.

**Review by mrgrain — APPROVED** [review]

**Pull request merged**
